version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'police'
    ports:
      - 127.0.0.1:5432:5432
